package websocket;

public enum CommunicatorWebSocketMessageOperation {
    PLACESHIP,
    REMOVESHIP,
    REMOVEALLSHIPS,
    PLACESHIPSAUTO,
    SHOWPLAYERFIELD,
    SHOWOPPONENTPLAYERFIELD,
    FIRESHOT,
    SHOTFIRERESPONSE,
    NOTIFYWHENREADY,
    REGISTERACCOUNT,
    REGISTERACCOUNTRESPONSESINGLE,
    PLAYERREADY,
    SHOTRECEIVE,
    WAITFOROTHERPLAYER,
    GAMENOTFOUNDERROR,
    SETPLAYER,
    SETPLAYEROPPONENT,
    STARTGAMEMULTIPLAYER,
    PLAYERNOTREADY,
    STARTGAMESINGLEPLAYER,
    SWITCHTURN;
}
